### ISSUE TITLE
always have 200

### ISSUE THREAD

**Issue by junchaozhang** [o2team/koa-joi-router-docs#1]
![image](https://user-images.githubusercontent.com/6490080/30153825-6cc56af6-93ea-11e7-98ff-936979c24758.png)

can we remove the 200 when we have other http status code?

**Comment by chuyik** [comment]
I can't get what you mean, where's the 200 in your screenshot?

**Comment by Eronana** [comment]
`lib/generator.js:70`:
```javascript
  let routeDesc = {
    responses: {
      200: {
        description: 'Success'
      }
    }
  };
```
200 is default status code and we cannot remove it.
Sometimes we needn't 200, we just response 204, but we will get two response docs 200 and 204 finally, because 200 is always existing.

**Comment by esdoppio** [comment]
I have the same problem here. Sometimes I just don't need 200. The other problem that I have is, sometimes I just want to document the output, but I don't want Joi to validate it. Is it possible to place `output` outside of `validate` and still generate the doc of output?

**Comment by chuyik** [comment]
@Eronana Yeah it's true, and I just got your contribution, thanks for that. I shall validate it tonight.

@esdoppio Maybe we need a new param named `skipValidate`, like this:
```js
router.get('/signup', {
  validate: {
    type: 'json',
    body: {
      ...
    },
    output: {
      ...
    }
  },
  skipValidate: 'output'  // or array ['output', 'body']
})
```
What do you think?

**Comment by esdoppio** [comment]
That means you need to alter the behavior of Joi? Doesn't seem really necessary if so.

**Comment by chuyik** [comment]
No, of course not.
What I try to add is just a `skipValidate` option, which won't be passed to Joi, but can be used in `lib/generator` to judge if we need Joi to do the validation jobs.

**Comment by Eronana** [comment]
I think option `outputFunc` in [my PR](https://github.com/o2team/koa-joi-router-docs/pull/2) can solve this problem without `skipValidate`.

**Comment by chuyik** [comment]
Hey guys, now you can use option `defaultResponses` to avoid the default 200, see [README](https://github.com/o2team/koa-joi-router-docs#swaggerapigeneratespecbasespec-options) or [example](https://github.com/o2team/koa-joi-router-docs/blob/master/example/routes.js#L90).

And `output` outside of validate is recognized now, if you just want to document the output without validation.
Example: 
```js
router.get('/user', {
  // This WILL be documented (take precedence over validate.output)
  output: {
    ...
  },
  validate: {
    query: {
      ...
    },
    // This WILL NOT be documented if output is also placed outside, but still validated
    output: {
      ...
    }
  },
})
```

Please check out v0.1.4 now if you need it. Cheers.
